#!/usr/bin/env bash
# Bootstrap: conan-server (Linux / Raspberry Pi host)
# Mounts the external package-storage disk (without touching its existing
# data), generates .env secrets on first run, and builds + starts the
# Dockerized Conan server.
# Usage: git clone <repo-url> && cd <repo>/conan-server/linux && sudo ./bootstrap.sh
# Must be idempotent: safe to run again on a machine that's already set up.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/../../lib/linux/common.sh"

require_root
log "Starting bootstrap for conan-server"

# ---- Tunables (override by exporting before the run) ------------------------
# UUID of the disk partition that stores packages (find yours with: blkid).
DISK_UUID="${CONAN_DISK_UUID:-DE5ECE7A5ECE4B4B}"   # Seagate Expansion 4TB, NTFS
DISK_FSTYPE="${CONAN_DISK_FSTYPE:-ntfs3}"
MOUNT_POINT="${CONAN_MOUNT_POINT:-/mnt/expansion}"
DATA_DIR="${CONAN_DATA_DIR:-$MOUNT_POINT/conan-server-data}"
PORT="${CONAN_PUBLIC_PORT:-9300}"
# Files on the (NTFS) mount get owned by the invoking user.
MOUNT_UID="${SUDO_UID:-1000}"
MOUNT_GID="${SUDO_GID:-1000}"

command_exists docker || { log "Docker is required - run docker/linux/bootstrap.sh first."; exit 1; }
docker compose version >/dev/null 2>&1 || { log "The Docker Compose plugin is required."; exit 1; }

# ---- 1. Persistent mount for the package disk -------------------------------
if [[ ! -e "/dev/disk/by-uuid/$DISK_UUID" ]]; then
    log "Disk with UUID $DISK_UUID is not connected - plug it in and re-run."
    exit 1
fi
if ! grep -q "UUID=$DISK_UUID" /etc/fstab; then
    cp /etc/fstab /etc/fstab.bak.conan-server
    echo "UUID=$DISK_UUID $MOUNT_POINT $DISK_FSTYPE defaults,nofail,uid=$MOUNT_UID,gid=$MOUNT_GID,umask=022 0 0" >> /etc/fstab
    systemctl daemon-reload
    log "Added $MOUNT_POINT to /etc/fstab (backup: /etc/fstab.bak.conan-server)"
else
    log "fstab entry for UUID=$DISK_UUID already present, skipping"
fi
mkdir -p "$MOUNT_POINT"
mountpoint -q "$MOUNT_POINT" || mount "$MOUNT_POINT"
mkdir -p "$DATA_DIR"
log "Package storage: $DATA_DIR ($(df -h --output=avail "$MOUNT_POINT" | tail -1 | tr -d ' ') free)"

# ---- 2. Secrets / server config (.env) --------------------------------------
ENV_FILE="$SCRIPT_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    ci_password="$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))')"
    host_ip="$(hostname -I | awk '{print $1}')"
    cat > "$ENV_FILE" <<EOF
# Generated by bootstrap.sh on $(date '+%Y-%m-%d'). NOT committed to git.
# See .env.example for what each variable means.
CONAN_SERVER_USERS=ci:$ci_password
CONAN_WRITE_USERS=ci
CONAN_READ_USERS=?
CONAN_JWT_SECRET=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
CONAN_UPDOWN_SECRET=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
CONAN_PUBLIC_HOSTNAME=$host_ip
CONAN_PUBLIC_PORT=$PORT
CONAN_DATA_DIR=$DATA_DIR
EOF
    chown "$MOUNT_UID:$MOUNT_GID" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    log "Generated $ENV_FILE (user 'ci' with a random password - see the file)"
else
    log ".env already exists, keeping it"
fi

# ---- 3. Build and start the server ------------------------------------------
(cd "$SCRIPT_DIR" && docker compose up -d --build)

# ---- 4. Wait until it answers -----------------------------------------------
log "Waiting for the server to answer on port $PORT ..."
for _ in $(seq 1 30); do
    if curl -fsS "http://127.0.0.1:$PORT/v1/ping" >/dev/null 2>&1; then
        log "Conan server is up."
        "$SCRIPT_DIR/connection-info.sh"
        exit 0
    fi
    sleep 2
done
log "Server did not answer after 60s - check: docker logs conan-server"
exit 1
