#!/usr/bin/env bash
# Bootstrap: conan-server (Linux / Raspberry Pi host)
# Mounts the external package-storage disk (without touching its existing
# data), generates .env secrets on first run, and builds + starts the
# Dockerized Conan server.
# Usage: git clone <repo-url> && cd <repo>/conan-server/linux && sudo ./bootstrap.sh
# Must be idempotent: safe to run again on a machine that's already set up.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/../../lib/linux/common.sh"

require_root
log "Starting bootstrap for conan-server"

# ---- Tunables (override by exporting before the run) ------------------------
# UUID of the disk partition that stores packages (find yours with: blkid).
DISK_UUID="${CONAN_DISK_UUID:-DE5ECE7A5ECE4B4B}"   # Seagate Expansion 4TB, NTFS
DISK_FSTYPE="${CONAN_DISK_FSTYPE:-ntfs3}"
MOUNT_POINT="${CONAN_MOUNT_POINT:-/mnt/expansion}"
DATA_DIR="${CONAN_DATA_DIR:-$MOUNT_POINT/conan-server-data}"
PORT="${CONAN_PUBLIC_PORT:-9300}"
# Files on the (NTFS) mount get owned by the invoking user.
MOUNT_UID="${SUDO_UID:-1000}"
MOUNT_GID="${SUDO_GID:-1000}"

command_exists docker || { log "Docker is required - run docker/linux/bootstrap.sh first."; exit 1; }
docker compose version >/dev/null 2>&1 || { log "The Docker Compose plugin is required."; exit 1; }

# ---- 0. Sync toolchain versions with ConanAutomation ------------------------
# The conan-server version (and python base image) must ALWAYS match the
# toolchain pinned in ftdeps/model.py of FurkanTuzemen/ConanAutomation, so the
# server tracks whatever Conan the automation/CI uses. Every run re-reads the
# pin; if the repo is unreachable the existing .env values are kept.
CONAN_AUTOMATION_REPO="${CONAN_AUTOMATION_REPO:-git@github.com:FurkanTuzemen/ConanAutomation.git}"
sync_user="${SUDO_USER:-$(id -un)}"
synced_conan=""
synced_python=""
tmp_dir="$(sudo -u "$sync_user" mktemp -d)"
if sudo --preserve-env=SSH_AUTH_SOCK -u "$sync_user" \
        git clone --quiet --depth 1 "$CONAN_AUTOMATION_REPO" "$tmp_dir/ConanAutomation" 2>/dev/null; then
    model_py="$tmp_dir/ConanAutomation/ftdeps/model.py"
    synced_conan="$(grep -Eo 'conan_version: str = "[^"]+"' "$model_py" | head -n1 | grep -Eo '[0-9][0-9.]*' || true)"
    synced_python="$(grep -Eo 'python_version: str = "[^"]+"' "$model_py" | head -n1 | grep -Eo '[0-9][0-9.]*' || true)"
fi
rm -rf "$tmp_dir"
if [[ -n "$synced_conan" ]]; then
    log "ConanAutomation toolchain: conan $synced_conan, python ${synced_python:-3.11}"
else
    log "WARNING: could not read ConanAutomation - keeping the current version pin"
fi

# ---- 1. Persistent mount for the package disk -------------------------------
if [[ ! -e "/dev/disk/by-uuid/$DISK_UUID" ]]; then
    log "Disk with UUID $DISK_UUID is not connected - plug it in and re-run."
    exit 1
fi
if ! grep -q "UUID=$DISK_UUID" /etc/fstab; then
    cp /etc/fstab /etc/fstab.bak.conan-server
    echo "UUID=$DISK_UUID $MOUNT_POINT $DISK_FSTYPE defaults,nofail,uid=$MOUNT_UID,gid=$MOUNT_GID,umask=022 0 0" >> /etc/fstab
    systemctl daemon-reload
    log "Added $MOUNT_POINT to /etc/fstab (backup: /etc/fstab.bak.conan-server)"
else
    log "fstab entry for UUID=$DISK_UUID already present, skipping"
fi
mkdir -p "$MOUNT_POINT"
mountpoint -q "$MOUNT_POINT" || mount "$MOUNT_POINT"
mkdir -p "$DATA_DIR"
log "Package storage: $DATA_DIR ($(df -h --output=avail "$MOUNT_POINT" | tail -1 | tr -d ' ') free)"

# ---- 2. Secrets / server config (.env) --------------------------------------
ENV_FILE="$SCRIPT_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    ci_password="$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))')"
    host_ip="$(hostname -I | awk '{print $1}')"
    cat > "$ENV_FILE" <<EOF
# Generated by bootstrap.sh on $(date '+%Y-%m-%d'). NOT committed to git.
# See .env.example for what each variable means.
CONAN_SERVER_USERS=ci:$ci_password
CONAN_WRITE_USERS=ci
CONAN_READ_USERS=?
CONAN_JWT_SECRET=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
CONAN_UPDOWN_SECRET=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
CONAN_PUBLIC_HOSTNAME=$host_ip
CONAN_PUBLIC_PORT=$PORT
CONAN_DATA_DIR=$DATA_DIR
EOF
    chown "$MOUNT_UID:$MOUNT_GID" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    log "Generated $ENV_FILE (user 'ci' with a random password - see the file)"
else
    log ".env already exists, keeping it"
fi

# Write the synced (or default) toolchain pin into .env - this is what the
# compose build args read.
set_env_var() {
    if grep -q "^$1=" "$ENV_FILE"; then
        sed -i "s|^$1=.*|$1=$2|" "$ENV_FILE"
    else
        echo "$1=$2" >> "$ENV_FILE"
    fi
}
current_conan="$(grep -E '^CONAN_SERVER_VERSION=' "$ENV_FILE" | cut -d= -f2 || true)"
set_env_var CONAN_SERVER_VERSION "${synced_conan:-${current_conan:-2.7.1}}"
current_python="$(grep -E '^CONAN_PYTHON_VERSION=' "$ENV_FILE" | cut -d= -f2 || true)"
set_env_var CONAN_PYTHON_VERSION "${synced_python:-${current_python:-3.11}}"
log "Server pinned to conan-server $(grep -E '^CONAN_SERVER_VERSION=' "$ENV_FILE" | cut -d= -f2)"

# ---- 3. Build and start the server ------------------------------------------
(cd "$SCRIPT_DIR" && docker compose up -d --build)

# ---- 4. Wait until it answers -----------------------------------------------
log "Waiting for the server to answer on port $PORT ..."
for _ in $(seq 1 30); do
    if curl -fsS "http://127.0.0.1:$PORT/v1/ping" >/dev/null 2>&1; then
        log "Conan server is up."
        "$SCRIPT_DIR/connection-info.sh"
        exit 0
    fi
    sleep 2
done
log "Server did not answer after 60s - check: docker logs conan-server"
exit 1
